application: assignment1-973
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  script: queryForm.app

- url: /app
  script: app.app

libraries:
- name: webapp2
  version: latest
- name: MySQLdb
  version: latest
- name: jinja2
  version: latest
